### ISSUE TITLE
call getText without passing callback function

### ISSUE THREAD

**Issue by sadrzadehsina** [traviskaufman/node-lipsum#1]
I am wondering is there any way to call `getText` method without passing any callback function like below:
```javascript
var test = lipsum.getText();
```
I know `getText` is an async method, but I believe that in some situations a sync version of `getText` is required.

**Comment by traviskaufman** [comment]
I'm afraid it's not possible. `getText` uses node's [http](https://nodejs.org/api/http.html) module under the hood, which does not provide a way to make synchronous requests. This makes sense when you think about it, because blocking intra-network IO would stall the entire runtime while it was executing. 

Maybe try and take a look at using [thunks](https://www.npmjs.com/package/thunks)? You could pass around the thunk as a value and then execute the callback when needed.

```javascript
var thunkify = require('thunks').thunkify;
var getText = thunkify(lipsum.getText.bind(lipsum));

var test = getText();

// some stuff...

test(function(text) { /* ... */ });
```
